name: cacheuk
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pytorch=2.0.1 # available on Windows
  - cpuonly
  - sentencepiece
  - pandas
  - matplotlib
  - pip
  - pip:
      - transformers==4.51.0
      - peft==0.11.0
      - datasets==2.19.1
      - accelerate==1.9.0
      - einops==0.7.0
      - yfinance==0.2.39
      - feedparser==6.0.11
      - unstructured==0.13.4
      - jupyterlab
